server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(api|auth|internal)(/|$) {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/admin/(nhap-diem|student|students|fac|hocphan|lop|sinhvien)(/|$) {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /login { proxy_pass http://backend:3000; }
    location = /student { proxy_pass http://backend:3000; }
    location = /student/update { proxy_pass http://backend:3000; }
    location = /classes { proxy_pass http://backend:3000; }
    location = /faculty { proxy_pass http://backend:3000; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
